FROM golang:1.26-alpine AS build

WORKDIR /app

COPY go.mod ./
COPY .env ./
RUN go mod download

COPY . .
RUN go build -o backend .

# Runtime
FROM alpine:3.19

WORKDIR /app

COPY --from=build /app/backend .

EXPOSE ${WEB_PORT}

CMD ["./backend"]
