FROM golang:1.22-alpine AS build

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . .
RUN go build -o backend .

# Runtime
FROM alpine:3.19

WORKDIR /app

COPY --from=build /app/backend .

EXPOSE 8080

CMD ["./backend"]
