services:
  # ── SvelteKit Frontend ──────────────────────────────────────────────────────
  frontend:
    build:
      context: ./server/frontend
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
        VITE_WEB_PORT: ${VITE_WEB_PORT}
        VITE_SERVER_URL: ${VITE_SERVER_URL}
        VITE_FALL_EVENT_TOPIC: ${VITE_FALL_EVENT_TOPIC}
        VITE_ALERT_TOPIC: ${VITE_ALERT_TOPIC}
        VITE_WEARABLE_IMU_TOPIC_PREFIX: ${VITE_WEARABLE_IMU_TOPIC_PREFIX}
        VITE_ALERT_UPDATE_TOPIC: ${VITE_ALERT_UPDATE_TOPIC}
        VITE_ROOM_SENSOR_TOPIC_PREFIX: ${VITE_ROOM_SENSOR_TOPIC_PREFIX}
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    networks:
      - iot-network

  postgres:
    image: postgres:18.3-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_volume:/var/lib/postgresql:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${DB_NAME} -h localhost || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - iot-network

  # ── Go Backend ───────────────────────────────────────────────────────────────
  backend:
    build:
      context: ./server/backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      DB_USER: ${DB_POSTGRES_USER}
      PORT: ${WEB_PORT}
    env_file:
      - .env
    networks:
      - iot-network
    depends_on:
      postgres:
        condition: service_healthy

  # ── Node-RED ─────────────────────────────────────────────────────────────────
  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    ports:
      - "1880:1880"
    volumes:
      - ./server/nodered/data:/data
    environment:
      - TZ=Europe/Tallinn
    networks:
      - iot-network
    restart: unless-stopped

  pgadmin:
    image: elestio/pgadmin:latest
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - "5050:8080"
    env_file:
      - .env
    volumes:
      - pgadmin_volume:/var/lib/pgadmin:rw
    depends_on:
      - postgres
    networks:
      - iot-network

volumes:
  pg_volume:
  pgadmin_volume:
    driver: local

networks:
  iot-network:
    driver: bridge
