<script lang="ts">
  import PatientList from '$components/PatientList.svelte';
  import PatientItem from '$components/PatientItem.svelte';

  type Severity = 'high' | 'medium' | 'low' | 'none';

  // Patient list generated by AI, not from real data
  const patients: {
    id: number;
    name: string;
    patientId: string;
    roomName: string;
    severity: Severity;
    lastEvent?: string;
    lastEventTime?: string;
  }[] = [
    { id: 1, name: 'Emily White',    patientId: '56438', roomName: 'Room 310', severity: 'high',   lastEvent: 'Fall',      lastEventTime: '09:33' },
    { id: 2, name: 'John Tart',      patientId: '98371', roomName: 'Room 420', severity: 'high',   lastEvent: 'Fall',      lastEventTime: '09:40' },
    { id: 3, name: 'Jane Doe',       patientId: '71624', roomName: 'Room 414', severity: 'medium', lastEvent: 'High temp', lastEventTime: '09:15' },
    { id: 4, name: 'Anne Smith',     patientId: '81276', roomName: 'Room 211', severity: 'low',    lastEvent: 'Motion',    lastEventTime: '08:52' },
    { id: 5, name: 'Lilly Whatson',  patientId: '72156', roomName: 'Room 613', severity: 'none' },
    { id: 6, name: 'Jacky Maron',    patientId: '87638', roomName: 'Room 723', severity: 'none' },
    { id: 7, name: "Martha O'Neil",  patientId: '74832', roomName: 'Room 613', severity: 'none' },
    { id: 8, name: 'Sofi Torren',    patientId: '12673', roomName: 'Room 613', severity: 'none' },
  ];

  let selectedId = $state<number | null>(null);
</script>

<div class="flex flex-1">
  <div class="w-72 flex flex-col">
    <PatientList title="Patients" count={patients.length}>
      {#each patients as p (p.id)}
        <PatientItem
          name={p.name}
          patientId={p.patientId}
          roomName={p.roomName}
          severity={p.severity}
          lastEvent={p.lastEvent}
          lastEventTime={p.lastEventTime}
          selected={selectedId === p.id}
          onclick={() => selectedId = p.id}
        />
      {/each}
    </PatientList>
  </div>

</div>