<script lang="ts">

  import { tryParsePatient, type Patient } from '../types/healthcare-db-types';
  import PatientList from '$components/PatientList.svelte';
  import PatientItem from '$components/PatientItem.svelte';
  import Alerts from '$components/Alerts.svelte';
  import AlertItem from '$components/AlertItem.svelte';
  import { onMount } from 'svelte';
  import { alertsStore } from '$stores/alerts.ts';
  import { Alert } from "flowbite-svelte";
  import { InfoCircleSolid } from "flowbite-svelte-icons";
    import { fetcher } from '../utils/fetcher';


  type Severity = 'high' | 'medium' | 'low' | 'none';





  // Patient list generated by AI, not from real data
  let patients: Patient[] = $state([]);

  let selectedId = $state<number | null>(null);

  onMount(async () => {
    // Fetch patients from the backend
    try {
      const response = (await fetcher('/patient')).data;
      console.log('Fetched patients:', response);
      // Assuming the response is an array of patients with the expected structure
      const parsedPatients = response.map((p: unknown) => tryParsePatient(p)).filter((result: any) => result.success).map((result: any) => result.data);
      patients = parsedPatients;
      console.log('Parsed patients:', parsedPatients);
    } catch (error) {
      console.error('Error fetching patients:', error);
    }
  });
</script>

<div class="flex flex-1 w-full">
  <div class="w-md flex flex-col flex-1">
    <PatientList title="Patients" count={patients.length}>
      {#each patients as p (p.ID)}
        <PatientItem
          name={p.name}
          patientId={p.patient_id}
          roomName={p.room?.room_name || 'Unassigned'}
          // severity={p.severity}
          // lastEvent={p.lastEvent}
          // lastEventTime={p.lastEventTime}
          selected={selectedId === p.ID}
          onclick={() => selectedId = p.ID}
        />
      {/each}
    </PatientList>
  </div>
</div>

